/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haloai_hud_hudendpoint_arwaylib_utils_EnlargedCrossProcess */

#ifndef _Included_com_haloai_hud_hudendpoint_arwaylib_utils_EnlargedCrossProcess
#define _Included_com_haloai_hud_hudendpoint_arwaylib_utils_EnlargedCrossProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_haloai_hud_hudendpoint_arwaylib_utils_EnlargedCrossProcess
 * Method:    nativeGetBranchRoads
 * Signature: (JILcom/haloai/hud/hudendpoint/arwaylib/utils/EnlargedCrossProcess/PointA;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_haloai_hud_hudendpoint_arwaylib_utils_EnlargedCrossProcess_nativeGetBranchRoads
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     com_haloai_hud_hudendpoint_arwaylib_utils_EnlargedCrossProcess
 * Method:    nativeGetHopPointInCrossImage
 * Signature: (JLcom/haloai/hud/hudendpoint/arwaylib/utils/EnlargedCrossProcess/PointA;)I
 */
JNIEXPORT jint JNICALL Java_com_haloai_hud_hudendpoint_arwaylib_utils_EnlargedCrossProcess_nativeGetHopPointInCrossImage
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
