/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haloai_hud_hudendpoint_arwaylib_utils_EnlargedCrossProcess_Size2i */

#ifndef _Included_com_haloai_hud_hudendpoint_arwaylib_utils_EnlargedCrossProcess_Size2i
#define _Included_com_haloai_hud_hudendpoint_arwaylib_utils_EnlargedCrossProcess_Size2i
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
